---
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: fleetman
servers: 1 # 1 master node
agents: 2 # 2 worker nodes
kubeAPI:
  hostIP: "0.0.0.0"
  hostPort: "6446"
volumes:
  - volume: ${CURRENT_DIR}/manifests:/var/lib/rancher/k3s/server/manifests/ # On deploie automatiquement les manifests
    nodeFilters:
      - server:*
ports:
  - port: 8888:32080 # On ouvre un port sur notre machine locale vers le port NodePort du service web-app
    nodeFilters:
      - agent:*
options:
  k3d:
    wait: true
    timeout: 2m0s
    disableLoadbalancer: false
    disableImageVolume: false
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --disable=metrics-server
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true 

