providers:
  - name: "k0smotron"
    url: "https://github.com/k0sproject/k0smotron/releases/latest/bootstrap-components.yaml"
    type: "BootstrapProvider"
  - name: "k0smotron"
    url: "https://github.com/k0sproject/k0smotron/releases/latest/control-plane-components.yaml"
    type: "ControlPlaneProvider"
  - name: "k0smotron"
    url: "https://github.com/k0sproject/k0smotron/releases/latest/infrastructure-components.yaml"
    type: "InfrastructureProvider"