apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: mgmt-cluster
servers: 1
agents: 0
kubeAPI:
  hostIP: "0.0.0.0"
  hostPort: "6446"
image: rancher/k3s:v1.27.4-k3s1
volumes:
  - volume: /home/fred/Documents/git/gitlab-gentle/k3s-quanti/post-install/:/var/lib/rancher/k3s/server/manifests/
    nodeFilters:
      - server:*
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: 2m0s
    disableLoadbalancer: false
    disableImageVolume: false
  k3s:
    extraArgs:
      - arg: --tls-san=127.0.0.1
        nodeFilters:
          - server:*
      - arg: --disable=traefik
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
