version: '3'

tasks:
  install-k3d:
    desc: Install le binaire k3d
    cmds:
      - |
        wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

  deploy-k3d:
    desc: Deploie le cluster Kubernetes avec k3d
    vars:
      CURRENT_DIR:
        sh: pwd
    cmds:
      - |
        echo "Génération du fichier de configuration K3d..."
        export CURRENT_DIR={{.CURRENT_DIR}}
        envsubst < cluster.yaml > k3d.yaml
        echo "Configuration générée dans 'k3d-config.yaml'"
        k3d cluster create --config k3d.yaml

  delete-k3d:
    desc: Detruit le cluster Kubernetes avec k3d
    cmds:
      - |
        k3d cluster delete --config k3d.yaml
