---
version: '3'
tasks:
  install-k3d:
    desc: Install le binaire k3d
    cmds:
      - |
        wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

  create-cluster:
    desc: Deploie le cluster Kubernetes avec k3d
    vars:
      CURRENT_DIR:
        sh: pwd
    cmds:
      - |
        export CURRENT_DIR={{.CURRENT_DIR}}
        envsubst < cluster.yaml > k3d.yaml
        k3d cluster create --config k3d.yaml

  delete-cluster:
    desc: Detruit le cluster Kubernetes avec k3d
    cmds:
      - |
        k3d cluster delete --config k3d.yaml

  gen-secret:
    desc: Cree un secret Kubernetes pour l'authentification docker hub
    vars:
      DOCKERUSER: '{{ .DOCKERUSER | default "admin" }}'
      DOCKERPWD: '{{ .DOCKERPWD | default "password" }}'
    cmds:
      - |
        kubectl create secret docker-registry dockerhub-creds \
            --docker-username={{ .DOCKERUSER }} \
            --docker-password={{ .DOCKERPWD }} \
            --docker-server=https://docker.io \
            --namespace=default --dry-run=client -oyaml > manifests/secret.yaml
